animes_gender_options = (
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Ecchi",
    "Fantasy",
    "Harem",
    "Hentai",
    "Historical",
    "Horror",
    "Isekai",
    "Josei",
    "Martial Arts",
    "Mecha",
    "Music",
    "Mystery",
    "Parody",
    "Psychological",
    "Romance",
    "School",
    "Science Fiction",
    "Seinen",
    "Shoujo",
    "Shounen",
    "Slice of Life",
    "Sports",
    "Super Power",
    "Supernatural",
    "Yaoi",
    "Yuri",
    "Other",
)


films_series_gender_options = (
    "Action",
    "Adventure",
    "Adventure-Comedy",
    "Animation",
    "Biography",
    "Comedy",
    "Crime",
    "Crime-Drama",
    "Documentary",
    "Drama",
    "Fantasy",
    "Fantasy-Adventure",
    "Family",
    "History",
    "Horror",
    "Music",
    "Musical",
    "Mystery",
    "Romance",
    "Romantic Comedy",
    "Science Fiction",
    "Sci-Fi Horror",
    "Sport",
    "Superhero",
    "Supernatural",
    "Thriller",
    "War",
    "Western"
    "Other",
)
